@startuml
'https://plantuml.com/sequence-diagram

'hide circle
scale 400 height
skinparam RoundCorner 0
skinparam classFontColor 76d43e
skinparam classBackgroundColor fff
skinparam classFontStyle bold
skinparam classAttributeIconSize 0
skinparam ArrowColor 76d43e
hide empty members

abstract class User {
    # string name
}
 interface AuthInterface {
    + auth(string $login, string $password): bool
 }

class Member extends User implements AuthInterface {
    # string login
    # string password
    # int age
}

@enduml
